version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m app.main  # Run as module
    ports:
      - "7001:7001"  # Changed from 5000:5000 to 7001:7001
    volumes:
      - ./books:/app/books
      - ./app/config.json:/app/app/config.json
    environment:
      - DATABASE_URL=postgresql://user:password@db/library
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev --prefix /app/frontend -- --host  # Add --host
    ports:
      - "8081:8081"  
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - app
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"  # Map pgAdmin to localhost:5050
    depends_on:
      - db
volumes:
  pgdata: